name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Testing
    strategy:
      matrix:
        node-version: [20.x, 22.x]
      max-parallel: 1

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            mern/server/package-lock.json
            mern/client/package-lock.json

      - name: Install server npm packages
        run: npm ci
        working-directory: mern/server

      - name: Install client npm packages
        run: npm ci
        working-directory: mern/client

      - name: Start server in the background
        env:
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
        run: |
          echo "ATLAS_URI=$ATLAS_URI" > config.env
          npm start &
        working-directory: mern/server

      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: mern/client
          start: npm run dev
          wait-on: 'http://localhost:5173'
        
